CC = gcc
ARCH = -m32
CFLAGS = -Wall -pedantic -m32 -std=c99
LDFLAGS = $(ARCH)

lab06:		lab06.o printmsg.o

lab06.o:	lab06.c


.PHONY: x
x:		$(info -- cleaning the directory --)	
		rm -f lab06.o lab06

